title:			ral-arturo.org
email:			arturo.borrero.glez@gmail.com
description:		ral-arturo blog, about free software, debian, networks, systems, or whatever
baseurl:		""
url:			"http://ral-arturo.org"
twitter_username:	arturoborrero
github_username:	aborrero
markdown:		kramdown

#
# other settings
#
excerpt_separator:	<!--more-->
