title: ral-arturo.org
email: arturo.borrero.glez@gmail.com
description: ral-arturo blog
baseurl: ""
url: "http://aborrero.github.io/ral-arturo.org"
twitter_username: arturoborrero
github_username:  aborrero
markdown: kramdown
