title:			ral-arturo.org
email:			arturo@debian.org
description:		ral-arturo blog, about free software, debian, networks, systems, or whatever
baseurl:		""
url:			"http://ral-arturo.org"
twitter_username:	arturoborrero
github_username:	aborrero
markdown:		kramdown

#
# pagination config
#
gems:			[jekyll-paginate]
paginate:		15
paginate_path:		"/page:num/"

#
# other settings
#
excerpt_separator:	<!--more-->
