title:			ral-arturo.org
email:			arturo.bg@arturo.bg
description:		ral-arturo blog, about free software, debian, networks, systems, or whatever
baseurl:		""
url:			"https://ral-arturo.org"
github_username:	aborrero
markdown:		kramdown
mastodon_username: arturobg
mastodon_server: mas.to

#
# pagination config
#
plugins:		[jekyll-paginate, kramdown-parser-gfm]
paginate:		14
paginate_path:		"/page:num/"

#
# other settings
#
excerpt_separator:	<!--more-->
